const BASE_URL_LOCAL = 'http://localhost:8080';
const BASE_URL_GLOBAL = 'https://tu.dominio.goblal.de.docker';

const BASE_URL = BASE_URL_LOCAL + "/veterinaria";

export const API_URL = {
  auth : {
    login: `${BASE_URL}/login`,
    verify: `${BASE_URL}/verify`,
    usuario: `${BASE_URL}/usuario`,
  },
  panel : {
    total_tratamientos: `${BASE_URL}/panel/tratamientos`,
    total_clientes: `${BASE_URL}/panel/clientes`,
    total_mascotas: `${BASE_URL}/panel/mascotas`,
    total_banios: `${BASE_URL}/panel/banios`,
    total_citas: `${BASE_URL}/panel/citas`,
    total_boletas: `${BASE_URL}/panel/boletas`,
  },
  backup: {
    download: `${BASE_URL}/backup/download`,
  },
  usuarios : {
    find_all: `${BASE_URL}/usuarios`,
    find_all_custom: `${BASE_URL}/usuarios/custom`,
    find_all_mapper: `${BASE_URL}/usuarios/mapper`,
    find_by_id: (id: number) => `${BASE_URL}/usuarios/${id}`,
    insert: `${BASE_URL}/usuarios`,
    update: (id: number) => `${BASE_URL}/usuarios/${id}`,
    delete: (id: number) => `${BASE_URL}/usuarios/${id}`,
  },
  roles : {
    find_all: `${BASE_URL}/roles`,
    find_all_custom: `${BASE_URL}/roles/custom`,
    find_all_mapper: `${BASE_URL}/roles/mapper`,
    find_by_id: (id: number) => `${BASE_URL}/roles/${id}`,
    insert: `${BASE_URL}/roles`,
    update: (id: number) => `${BASE_URL}/roles/${id}`,
    delete: (id: number) => `${BASE_URL}/roles/${id}`,
  },
  clientes : {
    find_all: `${BASE_URL}/clientes`,
    find_all_custom: `${BASE_URL}/clientes/custom`,
    find_all_mapper: `${BASE_URL}/clientes/mapper`,
    find_by_id: (id: number) => `${BASE_URL}/clientes/${id}`,
    insert: `${BASE_URL}/clientes`,
    update: (id: number) => `${BASE_URL}/clientes/${id}`,
    delete: (id: number) => `${BASE_URL}/clientes/${id}`,
    set_foto: (id: number) => `${BASE_URL}/clientes/setFoto/${id}`,
  },
  banios : {
    find_all: `${BASE_URL}/banios`,
    find_all_custom: `${BASE_URL}/banios/custom`,
    find_all_mapper: `${BASE_URL}/banios/mapper`,
    find_all_by_mascota_id: (id: number) => `${BASE_URL}/banios/mascota_id/${id}`,
    find_by_id: (id: number) => `${BASE_URL}/banios/${id}`,
    insert: `${BASE_URL}/banios`,
    update: (id: number) => `${BASE_URL}/banios/${id}`,
    delete: (id: number) => `${BASE_URL}/banios/${id}`,
    set_foto_entrada: (id: number) => `${BASE_URL}/banios/setFotoEntrada/${id}`,
    set_foto_salida: (id: number) => `${BASE_URL}/banios/setFotoSalida/${id}`,
  },
  productos : {
    find_all: `${BASE_URL}/productos`,
    find_all_custom: `${BASE_URL}/productos/custom`,
    find_all_mapper: `${BASE_URL}/productos/mapper`,
    find_by_id: (id: number) => `${BASE_URL}/productos/${id}`,
    insert: `${BASE_URL}/productos`,
    update: (id: number) => `${BASE_URL}/productos/${id}`,
    delete: (id: number) => `${BASE_URL}/productos/${id}`,
    set_foto: (id: number) => `${BASE_URL}/productos/setFoto/${id}`,
  },
  proveedores : {
    find_all: `${BASE_URL}/proveedores`,
    find_all_custom: `${BASE_URL}/proveedores/custom`,
    find_all_mapper: `${BASE_URL}/proveedores/mapper`,
    find_by_id: (id: number) => `${BASE_URL}/proveedores/${id}`,
    find_productos_by_id: (id: number) => `${BASE_URL}/proveedores/productos/${id}`,
    insert: `${BASE_URL}/proveedores`,
    update: (id: number) => `${BASE_URL}/proveedores/${id}`,
    delete: (id: number) => `${BASE_URL}/proveedores/${id}`,
    set_foto: (id: number) => `${BASE_URL}/proveedores/setFoto/${id}`,
  },
  mascotas : {
    find_all: `${BASE_URL}/mascotas`,
    find_all_custom: `${BASE_URL}/mascotas/custom`,
    find_all_mapper: `${BASE_URL}/mascotas/mapper`,
    find_all_by_cliente_id: (id: number) => `${BASE_URL}/mascotas/cliente_id/${id}`,
    find_by_id: (id: number) => `${BASE_URL}/mascotas/${id}`,
    insert: `${BASE_URL}/mascotas`,
    update: (id: number) => `${BASE_URL}/mascotas/${id}`,
    delete: (id: number) => `${BASE_URL}/mascotas/${id}`,
    set_foto: (id: number) => `${BASE_URL}/mascotas/setFoto/${id}`,
  },
  razas : {
    find_all: `${BASE_URL}/razas`,
    find_all_custom: `${BASE_URL}/razas/custom`,
    find_all_mapper: `${BASE_URL}/razas/mapper`,
    find_by_id: (id: number) => `${BASE_URL}/razas/${id}`,
    insert: `${BASE_URL}/razas`,
    update: (id: number) => `${BASE_URL}/razas/${id}`,
    delete: (id: number) => `${BASE_URL}/razas/${id}`,
  },
  tratamientos : {
    find_all: `${BASE_URL}/tratamientos`,
    find_all_custom: `${BASE_URL}/tratamientos/custom`,
    find_all_mapper: `${BASE_URL}/tratamientos/mapper`,
    find_all_by_mascota_id: (id: number) => `${BASE_URL}/tratamientos/mascota_id/${id}`,
    find_by_id: (id: number) => `${BASE_URL}/tratamientos/${id}`,
    insert: `${BASE_URL}/tratamientos`,
    update: (id: number) => `${BASE_URL}/tratamientos/${id}`,
    delete: (id: number) => `${BASE_URL}/tratamientos/${id}`,
  },
  citas : {
    find_all: `${BASE_URL}/citas`,
    find_all_custom: `${BASE_URL}/citas/custom`,
    find_all_mapper: `${BASE_URL}/citas/mapper`,
    find_all_by_mascota_id: (id: number) => `${BASE_URL}/citas/mascota_id/${id}`,
    find_all_by_estado: (estado: string) => `${BASE_URL}/citas/estado/${estado}`,
    find_by_id: (id: number) => `${BASE_URL}/citas/${id}`,
    insert: `${BASE_URL}/citas`,
    update: (id: number) => `${BASE_URL}/citas/${id}`,
    delete: (id: number) => `${BASE_URL}/citas/${id}`,
    cancelar: (id: number) => `${BASE_URL}/citas/cancelar/${id}`,
  },
  especies : {
    find_all: `${BASE_URL}/especies`,
    find_all_custom: `${BASE_URL}/especies/custom`,
    find_all_mapper: `${BASE_URL}/especies/mapper`,
    find_by_id: (id: number) => `${BASE_URL}/especies/${id}`,
    insert: `${BASE_URL}/especies`,
    update: (id: number) => `${BASE_URL}/especies/${id}`,
    delete: (id: number) => `${BASE_URL}/especies/${id}`,
  },
  categorias : {
    find_all: `${BASE_URL}/categorias`,
    find_all_custom: `${BASE_URL}/categorias/custom`,
    find_all_mapper: `${BASE_URL}/categorias/mapper`,
    find_by_id: (id: number) => `${BASE_URL}/categorias/${id}`,
    insert: `${BASE_URL}/categorias`,
    update: (id: number) => `${BASE_URL}/categorias/${id}`,
    delete: (id: number) => `${BASE_URL}/categorias/${id}`,
  },
  boletas : {
    find_all: `${BASE_URL}/boletas`,
    find_all_custom: `${BASE_URL}/boletas/custom`,
    find_all_mapper: `${BASE_URL}/boletas/mapper`,
    find_by_id: (id: number) => `${BASE_URL}/boletas/${id}`,
    find_new_id: `${BASE_URL}/boletas/new`,
    insert: `${BASE_URL}/boletas`,
    update: (id: number) => `${BASE_URL}/boletas/${id}`,
    delete: (id: number) => `${BASE_URL}/boletas/${id}`,
    anular: (id: number) => `${BASE_URL}/boletas/anular/${id}`,
    descargar: (id: number) => `${BASE_URL}/boletas/descargar/${id}`,
    previsualizar: (id: number) => `${BASE_URL}/boletas/previsualizar/${id}`,
  },
  pedidos : {
    find_all: `${BASE_URL}/pedidos`,
    find_all_custom: `${BASE_URL}/pedidos/custom`,
    find_all_mapper: `${BASE_URL}/pedidos/mapper`,
    find_by_id: (id: number) => `${BASE_URL}/pedidos/${id}`,
    find_new_id: `${BASE_URL}/pedidos/new`,
    insert: `${BASE_URL}/pedidos`,
    update: (id: number) => `${BASE_URL}/pedidos/${id}`,
    delete: (id: number) => `${BASE_URL}/pedidos/${id}`,
    anular: (id: number) => `${BASE_URL}/pedidos/anular/${id}`,
    recibir: (id: number) => `${BASE_URL}/pedidos/recibir/${id}`,
    descargar: (id: number) => `${BASE_URL}/pedidos/descargar/${id}`,
    previsualizar: (id: number) => `${BASE_URL}/pedidos/previsualizar/${id}`,
  },
  ingresos : {
    find_all_by_fecha: (fecha: string) => `${BASE_URL}/ingresos/${fecha}`,
    sum_total_by_fecha: (fecha: string) => `${BASE_URL}/ingresos/suma/${fecha}`,
  }
}
